eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path

from info_pages.views import page_view
from catalog.views import category_view, product_view, main_view, buy_view, cart_view, checkout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/<str:page_name>/', page_view, name="page_view"),
    path('category/<int:cat_id>/', category_view, name="cat_view"),
    path('item/<int:prod_id>/', product_view, name="prod_view"),
    path('item/<int:prod_id>/buy/', buy_view, name="buy_view"),
    path("cart/", cart_view, name="cart_view"),
    path("cart/checkout/", checkout_view, name="checkout_view"),
    path('', main_view, name="main_view"),
]

eshop/catalog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, null=False)
    description = models.TextField(null=True, blank=True, default='')

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=False)
    short_description = models.CharField(max_length=200, null=True, default='')
    description = models.TextField(null=True, blank=True, default='')
    price = models.PositiveIntegerField(default=0)
    small_photo = models.ImageField(null=True)
    big_photo = models.ImageField(null=True)
    is_enabled = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    is_really_hot = models.BooleanField(default=False)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return "{n} ({i})".format(n=self.name, i=self.id)

    def readable_price(self):
        true_price = self.price / 100
        return true_price

class Order(models.Model):
    code = models.CharField(max_length=30)
    person_name = models.CharField(max_length=200)
    person_email = models.EmailField()
    person_address = models.TextField()
    person_phone = models.CharField(max_length=30)
    notes = models.TextField(blank=True, null=True)
    status = models.ForeignKey('OrderStatus', on_delete=models.SET_NULL, null=True)
    comment = models.TextField(blank=True, null=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{i} ({d}, {pn})".format(i=self.id, d=self.order_date, pn=self.person_name)


class OrderStatus(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return "{i} ({d})".format(i=self.id, d=self.name)


class OrderedProduct(models.Model):
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Order: {n} ({i})".format(n=self.order, i=self.id)

    def readable_price(self):
        true_price = self.price / 100
        return true_price

eshop/catalog/forms.py
from django import forms

class CheckoutForm(forms.Form):
    person_name = forms.CharField(label="Ваше имя и фамилия", max_length=200, widget=forms.TextInput(attrs={"class": "form-control"}))
    person_email = forms.EmailField(label="Ваш E-Mail", widget=forms.EmailInput(attrs={"class": "form-control"}))
    person_phone = forms.CharField(label="Ваш номер телефона", max_length=30, widget=forms.TextInput(attrs={"class": "form-control", "type": "phone"}))
    person_address = forms.CharField(label="Адрес доставки (город, район, улица, дом, квартира или офис)", max_length=1024, widget=forms.Textarea(attrs={"rows": "3", "class": "form-control"}))
    notes = forms.CharField(label="Сообщение для оператора (можно не заполнять)", max_length=2048, required=False, widget=forms.Textarea(attrs={"rows": "5", "class": "form-control"}))

eshop/catalog/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from hashlib import md5
from datetime import datetime
from random import randint
from .cart import Cart
from .forms import CheckoutForm
from .models import Category, Product, Order, OrderedProduct, OrderStatus


# Create your views here.
def category_view(request, cat_id):
    # 1. Получение информации из базы по запросу
    try:
        category = Category.objects.get(id=cat_id)
    except Category.DoesNotExist:
        raise Http404
    products = Product.objects.filter(category=category).exclude(is_enabled=False).order_by("name")
    categories = Category.objects.order_by("name")
    # 2. Подготовка контекста
    context = {
        "category": category,
        "categories": categories,
        "products": products,
    }
    # 3. Вывод результат
    return render(request, "category.html", context=context)


def product_view(request, prod_id):
    # 1. Получение информации из базы по запросу
    try:
        product = Product.objects.get(id=prod_id)
    except Product.DoesNotExist:
        raise Http404

    categories = Category.objects.order_by("name")
    # 2. Подготовка контекста
    context = {
        "categories": categories,
        "product": product,
    }
    # 3. Вывод результат
    return render(request, "product.html", context=context)


def main_view(request):
    # 1. Получение информации из базы по запросу
    products = Product.objects.filter(is_featured=True).exclude(is_enabled=False).order_by("name")
    hot_products = Product.objects.filter(is_really_hot=True).exclude(is_enabled=False).order_by("name")
    categories = Category.objects.order_by("name")
    # 2. Подготовка контекста
    context = {
        "categories": categories,
        "products": products,
        "hot_products": hot_products,
    }
    # 3. Вывод результат
    return render(request, "main.html", context=context)


def buy_view(request, prod_id):
    cart = Cart(request)
    try:
        product = Product.objects.get(id=prod_id)
    except Product.DoesNotExist:
        raise Http404
    cart.add_product(product)
    return HttpResponseRedirect(reverse("cart_view"))


def cart_view(request):
    CART_FIELD_PREFIX = "item_"
    cart = Cart(request)
    display_products = []
    total = 0
    if request.method == "POST":
        for field_name, field_value in request.POST.items():
            if field_name.startswith(CART_FIELD_PREFIX):
                try:
                    prod_id = int(field_name[len(CART_FIELD_PREFIX):])
                    product = Product.objects.get(id=prod_id)
                except ValueError:
                    continue
                except Product.DoesNotExist:
                    continue
                try:
                    qty = int(field_value)
                except ValueError:
                    qty = cart.quantity_by_id(prod_id)
                cart.update_product(product, qty)
                if qty > 0:
                    display_products.append({
                        "name": product.name,
                        "id": product.id,
                        "short_description": product.short_description,
                        "quantity": qty,
                        "subtotal": qty * product.price / 100,
                    })
                    total += qty * product.price

        if "go_back" in request.POST:
            return HttpResponseRedirect(reverse("main_view"))
        elif "do_order" in request.POST:
            return HttpResponseRedirect(reverse("checkout_view"))

    else:
        products = cart.products()
        for p in products:
            display_products.append({
                "name": p["product"].name,
                "id": p["product"].id,
                "short_description": p["product"].short_description,
                "quantity": p["quantity"],
                "subtotal": p["subtotal"] / 100,
            })
            total += p["subtotal"]

    display_products.sort(key=lambda p: p["name"])

    return render(request, "cart.html", context={"products": display_products, "total": total / 100})


def make_order_code(person_name):
    source_str = "{pn}{dt}{r}".format(pn=person_name, dt=datetime.now().isoformat(), r=randint(100000, 999999))
    hash_func = md5()
    hash_func.update(source_str.encode("utf-8"))
    return hash_func.hexdigest()

def checkout_view(request):
    cart = Cart(request)
    if cart.is_empty():
        return HttpResponseRedirect(reverse("cart_view"))
    if request.method == "POST":
        form = CheckoutForm(request.POST)
        if form.is_valid():
            order_code = make_order_code(form.cleaned_data["person_name"])
            try:
                order_status = OrderStatus(id=1)
            except:
                order_status = None
            order = Order(
                code=order_code, 
                person_name=form.cleaned_data["person_name"],
                person_email=form.cleaned_data["person_email"],
                person_phone=form.cleaned_data["person_phone"],
                person_address=form.cleaned_data["person_address"],
                notes=form.cleaned_data["notes"],
                status=order_status)
            order.save()
            for prod in cart.products():
                ordered_product = OrderedProduct(
                    order=order, 
                    product=prod["product"], 
                    quantity=prod["quantity"],
                    price=prod["product"].price)
                ordered_product.save()
            context = {
                "order_id": order.id,
                "person_email": form.cleaned_data["person_email"],
                "order_code": order_code,
            }
            cart.clear()

            # TODO: Отправка писем (покупателю и менеджеру)

            return render(request, "checkout_done.html", context=context)
    else:
        form = CheckoutForm()

    total = cart.total()
    return render(request, "checkout.html", context={"form": form, "total": total / 100})

eshop/catalog/templates/cart.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Корзина — Мой Магазин{% endblock %}
{% block left %}
    <p class="lead">Корзина</p>
{% endblock %}
{% block content %}
    {% if products %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th width="60%">Товар</th>
                        <th>Количество</th>
                        <th></th>
                        <th>Стоимость</th>
                    </tr>
                </thead>
                <tbody>
                {% for prod in products %}
                    <tr>
                        <td><a href="{% url 'prod_view' prod.id %}" title="{{ prod.short_description }}">{{ prod.name }}</a></td>
                        <td><input class="form-control input-sm" type="number" name="item_{{prod.id}}" value="{{prod.quantity}}" min="0"></td>
                        <td><input class="btn btn-default btn-sm" type="submit" name="update_cart" value="Сохранить"></td>
                        <td>{{prod.subtotal|intcomma}}</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">Итого</th>
                        <th>{{total|intcomma}} &#8381;</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <p class="help-block">Пожалуйста, не забудьте нажать кнопку «Сохранить», если вы изменили количество товара. Чтобы
        удалить товар из корзины, введите 0 в поле «Количество» и нажмите «Сохранить».</p>
        <div class="row">
            <div class="col-md-4">
                <input type="submit" class="btn btn-block btn-default btn-lg" name="go_back" value="Вернуться к покупкам">
            </div>
            <div class="col-md-4 col-md-offset-4">
                <input type="submit" class="btn btn-block btn-primary btn-lg" value="Оформить заказ" name="do_order">
            </div>
        </div>
    </form>
    {% else %}
    <div class="row">
        <p>В корзине пока что ничего нет. Чтобы добавить товар в корзину, перейдите на страницу этого товара и нажмите кнопку
        «Добавить в корзину».</p>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'main_view' %}" class="btn btn-block btn-default btn-lg">Вернуться к покупкам</a>
        </div>
    </div>
    {% endif %}
{% endblock %}

eshop/catalog/templates/category.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}{{category.name}} — Мой Магазин{% endblock %}
{% block left %}
                <p class="lead">Каталог</p>
                <div class="list-group">
                    {% for cat in categories %}
                    <a href="{% url 'cat_view' cat.id %}" class="list-group-item {% if cat == category %} active{% endif %}">{{ cat.name }}</a>
                    {% endfor %}
                </div>
{% endblock %}
{% block content %}
                <div class="row">
                    <p class="lead">{{category.name}}</p>
                    <p>{{category.description}}</p>
                </div>
                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <a href="{% url 'prod_view' product.id %}"><img width="320" height="150" src="{{product.small_photo.url}}" alt="Изображение {{product.name}}"></a>
                            <div class="caption">
                                <h6 class="pull-right">{{product.readable_price|intcomma}} &#8381;</h6>
                                <h4><a href="{% url 'prod_view' product.id %}">{{product.name}}</a>
                                </h4>
                                <p>{{product.short_description}}</p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>Извините, в этой категории пока нет товаров.</p>
                    {% endfor %}
                </div>
{% endblock %}

eshop/catalog/templates/checkout.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Оформление заказа — Мой Магазин{% endblock %}
{% block left %}
                <p class="lead">Оформление заказа</p>
{% endblock %}
{% block content %}
                <p class="lead">Пожалуйста, заполните все поля. Без этой информации мы не сможем привести вам ваши товары.</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_person_name">{{ form.person_name.label}}:</label>
                        {{ form.person_name}}
                    </div>
                    <div class="form-group">
                        <label for="id_person_email">{{ form.person_email.label}}:</label>
                        {{ form.person_email}}
                        <p class="help-block">Не волнуйтесь, мы никогда не шлём рекламных объявлений и прочий спам. На этот адрес
                        вам придёт информация о вашем заказе, чтобы вы её не потеряли.</p>
                    </div>
                    <div class="form-group">
                        <label for="id_person_phone">{{form.person_phone.label}}:</label>
                        {{form.person_phone}}
                        <p class="help-block">Этот номер будет использовать наш оператор <strong>только</strong> для срочных
                        звоноков о вашем заказе. Никаких SMS, никакой рекламы.</p>
                    </div>
                    <div class="form-group">
                        <label for="id_person_address">{{ form.person_address.label}}:</label>
                        {{ form.person_address}}
                    </div>
                    <div class="form-group">
                        <label for="id_notes">{{ form.notes.label }}:</label>
                        {{ form.notes }}
                        <p class="help-block">Здесь можно написать, например, что вам желательно доставить товар 1 апреля,
                        или что с 13:00 до 14:30 вас не будет дома, и любые другие уточнения.</p>
                    </div>

                    <p class="lead">К оплате: {{total|intcomma}} &#8381;.</p>

                    <p>Оплата осуществляется <strong>наличными</strong> нашему курьеру при получении товара. К сожалению,
                    безналичного расчёта у нас пока что нет.</p>

                    <div class="row">
                        <div class="col-md-4">
                            <a href="{% url 'cart_view' %}" class="btn btn-block btn-default btn-lg">Назад к корзине</a>
                        </div>
                        <div class="col-md-4 col-md-offset-4">
                            <input type="submit" class="btn btn-block btn-primary btn-lg" value="Оформить заказ">
                        </div>
                    </div>
                </form>
{% endblock %}

eshop/catalog/templates/main.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Мой Магазин{% endblock %}
{% block left %}
                <p class="lead">Каталог</p>
                <div class="list-group">
                    {% for cat in categories %}
                    <a href="{% url 'cat_view' cat.id %}" class="list-group-item">{{ cat.name }}</a>
                    {% endfor %}
                </div>
{% endblock %}
{% block content %}
                {% if hot_products %}
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for p in hot_products %}
                                <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for product in hot_products %}
                                <div class="item {% if forloop.first %}active{% endif %}">
                                    <a href="{% url 'prod_view' product.id %}">
                                        <img class="slide-image" src="{{ product.big_photo.url }}" alt="Фотография {{product.name}}">
                                        <div class="carousel-caption">
                                            <h3>{{product.name}}</h3>
                                            <p>{{product.short_description}}</p>
                                        </div>
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}

                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <a href="{% url 'prod_view' product.id %}"><img width="320" height="150" src="{{product.small_photo.url}}" alt="Изображение {{product.name}}"></a>
                            <div class="caption">
                                <h6 class="pull-right">{{product.readable_price|intcomma}} &#8381;</h6>
                                <h4><a href="{% url 'prod_view' product.id %}">{{product.name}}</a>
                                </h4>
                                <p>{{product.short_description}}</p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>Добро пожаловать в наш магазин! Пожалуйста, выберите категорию слева.</p>
                    {% endfor %}
                </div>
{% endblock %}

eshop/catalog/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}{{product.name}} — Мой Магазин{% endblock %}
{% block left %}
                <p class="lead">Каталог</p>
                <div class="list-group">
                    {% for cat in categories %}
                    <a href="{% url 'cat_view' cat.id %}" class="list-group-item {% if product.category == cat %} active{% endif %}">{{ cat.name }}</a>
                    {% endfor %}
                </div>
{% endblock %}
{% block content %}
                <div class="thumbnail">
                    <img class="img-responsive" src="{{product.big_photo.url}}" alt="Изображение {{product.name}}">
                    <div class="caption-full">
                        <h4 class="pull-right">{{product.readable_price|intcomma}} &#8381;</h4>
                        <h4>{{product.name}}
                        </h4>
                        <p>{{product.short_description}}</p>
                        <div>{{product.description|linebreaks}}</div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-8">
                        <a href="{% url 'buy_view' product.id %}" class="btn btn-primary btn-block">Положить в корзину</a>
                    </div>
                </div>
{% endblock %}